spring:
  application:
    name: importer
  datasource:
    url: jdbc:mysql://78.96.25.131:3306/test_db
    username: root
    password: R@0t
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: HikariPool
      minimum-idle: 5
      maximum-pool-size: 10
      idle-timeout: 60000
      connection-timeout: 30000
      max-lifetime: 1800000
  sql:
    init:
      mode: never
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    show-sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost/keycloak/realms/rsk/protocol/openid-connect/certs

  Kafka:
    bootstrap-servers: localhost:30001
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false

app:
  security:
    expected-issuer: http://localhost/keycloak/realms/rsk
  cors:
    allowed-origins: ${APP_CORS_ALLOWED_ORIGINS:http://localhost,http://localhost:3000,http://localhost:4200}
  kafka:
    topic: product-topic
  elk:
    elasticsearch-uri: https://resurse-app-elasticsearch:9200
    kibana-base-url: http://resurse-app-kibana:5601/kibana
    logstash-host: 127.0.0.1
    logstash-port: 30544

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

logging:
  config: classpath:logback-spring.xml

server:
  port: 8082
